### ISSUE TITLE
Session form submit button

### ISSUE THREAD

**Issue by m1010j** [Roots2D/thunk#1]
Your auth works and looks great! I would just style the submit button a bit more.

**Comment by CodesMcCabe** [comment]
I might have pushed to heroku slightly after you reviewed which will have an updated button. Or are you referring to the current button on heroku?

**Comment by m1010j** [comment]
Looks great now! I just noticed that you're not rendering any errors yet. Make sure to do that!

**Comment by CodesMcCabe** [comment]
Errors now render!

**Comment by m1010j** [comment]
You should style the errors a bit so that they look more like they do on the app you're cloning.

**Comment by m1010j** [comment]
I'm seeing errors when I'm clicking on the demo button. Also, the demo button should have more descriptive text.

**Comment by CodesMcCabe** [comment]
Updated. Had some issues getting awesomefont to work so I was unable to import the hazard icon upon error rendering.

**Comment by m1010j** [comment]
Looks great now!
